<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	  <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Renting_Website</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ClassLibrary\**" />
    <Content Remove="ClassLibrary\**" />
    <EmbeddedResource Remove="ClassLibrary\**" />
    <None Remove="ClassLibrary\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Westwind.AspNetCore.LiveReload" Version="0.5.0" />
	  <ProjectReference Include="..\BusinessLogic\BusinessLogic.csproj" />
  </ItemGroup>

</Project>
